# Generated by Django 6.1.1 on 2026-10-05 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, max_length=160, unique=True, verbose_name='شناسه یکتا (اسلاگ)')),
                ('product_type', models.CharField(choices=[('PHYSICAL', 'کالایی'), ('SERVICE', 'خدماتی')], default='PHYSICAL', max_length=20, verbose_name='نوع ماهیتی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات دسته')),
                ('suggested_attributes', models.JSONField(blank=True, default=list, help_text='لیست کلیدها و برچسب\u200cهای ویژگی\u200cها به صورت JSON', verbose_name='ویژگی\u200cهای پیش\u200cفرض این دسته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['product_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول یا خدمت')),
                ('product_type', models.CharField(choices=[('PHYSICAL', 'کالایی'), ('SERVICE', 'خدماتی')], default='PHYSICAL', max_length=20, verbose_name='نوع محصول')),
                ('description', models.TextField(verbose_name='شرح مزایا و کاربرد محصول')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت تقریبی (تومان)')),
                ('url', models.URLField(blank=True, verbose_name='لینک صفحه محصول')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='ویژگی\u200cهای اختصاصی دسته')),
                ('target_customer', models.TextField(blank=True, verbose_name='خریداران ایده\u200cآل (ICP)')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال برای کشف'), ('INACTIVE', 'غیرفعال')], default='ACTIVE', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='businesses.business', verbose_name='کسب\u200cوکار')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='دسته\u200cبندی سلسله\u200cمراتبی')),
            ],
            options={
                'verbose_name': 'محصول / خدمت',
                'verbose_name_plural': 'محصولات و خدمات',
                'ordering': ['-created_at'],
            },
        ),
    ]
