# Generated by Django 6.1.1 on 2026-10-05 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_daily_discovery_limit_and_more'),
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to='businesses.business', verbose_name='کسب\u200cوکار صاحب دسته'),
        ),
        migrations.AddField(
            model_name='product',
            name='discovery_priority',
            field=models.PositiveSmallIntegerField(default=1, help_text='اولویت پایش از ۱ (عادی) تا ۵ (فوری)', verbose_name='اولویت جستجو'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discovery_active',
            field=models.BooleanField(default=True, help_text='آیا این کالا در سهمیه جستجوی مشتری بالقوه قرار گیرد؟', verbose_name='فعال در پایش روزانه هوش مصنوعی'),
        ),
        migrations.AddField(
            model_name='product',
            name='telegram_outreach_enabled',
            field=models.BooleanField(default=True, verbose_name='ارتباط از طریق تلگرام'),
        ),
        migrations.AddField(
            model_name='product',
            name='x_outreach_enabled',
            field=models.BooleanField(default=True, verbose_name='ارتباط از طریق X (توییتر)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=160, verbose_name='شناسه یکتا (اسلاگ)'),
        ),
    ]
