# Generated by Django 6.1.1 on 2026-10-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_business_product_discovery_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='depth',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='عمق دسته\u200cبندی (۱ تا ۵)'),
        ),
        migrations.AddField(
            model_name='category',
            name='embedding',
            field=models.JSONField(blank=True, default=list, verbose_name='بردار تعبیه\u200cشده دسته (Embedding)'),
        ),
        migrations.AddField(
            model_name='category',
            name='embedding_model',
            field=models.CharField(blank=True, default='text-embedding-3-small', max_length=100, verbose_name='مدل بردارساز'),
        ),
        migrations.AddField(
            model_name='category',
            name='embedding_version',
            field=models.CharField(blank=True, default='v1', max_length=50, verbose_name='نسخه بردار'),
        ),
        migrations.AddField(
            model_name='category',
            name='full_path',
            field=models.CharField(blank=True, db_index=True, max_length=500, verbose_name='مسیر کامل دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='کلمات کلیدی و مترادف\u200cها'),
        ),
        migrations.AddField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام نرمال\u200cشده'),
        ),
        migrations.AddField(
            model_name='category',
            name='taxonomy_version',
            field=models.PositiveIntegerField(default=1, verbose_name='نسخه تاکسونومی'),
        ),
    ]
