# Generated by Django 6.1.2 on 2026-10-08 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_depth_category_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='category',
            name='embedding_model',
        ),
        migrations.RemoveField(
            model_name='category',
            name='embedding_version',
        ),
        migrations.RemoveField(
            model_name='category',
            name='taxonomy_version',
        ),
    ]
