# Generated by Django 6.1.2 on 2026-10-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_engine_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='agent_card_override',
            field=models.JSONField(blank=True, help_text='خالی = نسخه\u200cی خود ایجنت. پر = همین متن مستقیم در تطبیق استفاده می\u200cشود.', null=True, verbose_name='برداشت ایجنت (ویرایش\u200cشده توسط فروشنده)'),
        ),
    ]
