# Generated by Django 6.1.2 on 2026-10-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_agent_card_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='x_search_enabled',
            field=models.BooleanField(default=False, help_text='برای این محصول جداگانه در X جستجو و تحلیل می\u200cشود؛ هزینه از کیف پول کسر می\u200cشود.', verbose_name='جستجوی مشتری در X (توییتر)'),
        ),
    ]
