# Generated by Django 6.1.1 on 2026-10-05 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کسب\u200cوکار')),
                ('business_type', models.CharField(choices=[('PHYSICAL', 'کالایی / فروشگاهی'), ('SERVICE', 'خدماتی'), ('ONLINE', 'آنلاین / دیجیتال'), ('HYBRID', 'ترکیبی (کالایی و خدماتی)')], default='PHYSICAL', max_length=50, verbose_name='نوع کسب\u200cوکار')),
                ('business_domain', models.CharField(help_text='مثال: پوشاک و مد، برنامه\u200cنویسی و IT، آموزش آنلاین، لوازم دیجیتال', max_length=150, verbose_name='حوزه فعالیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات و ارزش پیشنهادی')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='موقعیت جغرافیایی / شهر')),
                ('target_customer_description', models.TextField(blank=True, verbose_name='شرح مشتریان ایده\u200cآل (ICP)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL, verbose_name='مالک کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'کسب\u200cوکار',
                'verbose_name_plural': 'کسب\u200cوکارها',
            },
        ),
    ]
