# Generated by Django 6.1.1 on 2026-10-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='daily_discovery_limit',
            field=models.PositiveIntegerField(default=5, verbose_name='سقف روزانه کالاهای فعال برای پایش'),
        ),
        migrations.AddField(
            model_name='business',
            name='preferred_outreach_mode',
            field=models.CharField(choices=[('DIRECT', 'دایرکت خصوصی'), ('COMMENT', 'کامنت و پاسخ عمومی')], default='DIRECT', max_length=20, verbose_name='روش ترجیحی ارسال پیام'),
        ),
        migrations.AddField(
            model_name='business',
            name='telegram_account_handle',
            field=models.CharField(blank=True, max_length=100, verbose_name='شناسه تلگرام فروشنده'),
        ),
        migrations.AddField(
            model_name='business',
            name='telegram_session_or_bot',
            field=models.CharField(blank=True, max_length=255, verbose_name='توکن یا سشن تلگرام'),
        ),
        migrations.AddField(
            model_name='business',
            name='x_access_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='توکن دسترسی X'),
        ),
        migrations.AddField(
            model_name='business',
            name='x_account_handle',
            field=models.CharField(blank=True, max_length=100, verbose_name='شناسه توییتر / X فروشنده'),
        ),
    ]
