# Generated by Django 6.1.1 on 2026-10-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_daily_discovery_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='daily_discovery_limit',
            field=models.PositiveIntegerField(default=50, verbose_name='سقف روزانه کالاهای فعال برای پایش'),
        ),
    ]
