# Generated by Django 6.1.1 on 2026-10-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_daily_discovery_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='target_locations',
            field=models.CharField(blank=True, default='سراسر کشور', max_length=255, verbose_name='موقعیت جغرافیایی و شهرهای هدف'),
        ),
        migrations.AddField(
            model_name='business',
            name='target_max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حداکثر سن مخاطب'),
        ),
        migrations.AddField(
            model_name='business',
            name='target_min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حداقل سن مخاطب'),
        ),
    ]
