# Generated by Django 6.1.1 on 2026-10-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_business_target_locations_business_target_max_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='catalog_version',
            field=models.PositiveIntegerField(default=1, verbose_name='نسخه کاتالوگ محصولات'),
        ),
        migrations.AddField(
            model_name='business',
            name='taxonomy_version',
            field=models.PositiveIntegerField(default=1, verbose_name='نسخه تاکسونومی دسته\u200cبندی\u200cها'),
        ),
    ]
