# Generated by Django 6.1.2 on 2026-10-08 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_catalog_version_business_taxonomy_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='catalog_version',
        ),
        migrations.RemoveField(
            model_name='business',
            name='taxonomy_version',
        ),
    ]
