# Generated by Django 6.1.2 on 2026-10-09 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_engine_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(choices=[('FORMAL', 'رسمی'), ('FRIENDLY', 'دوستانه'), ('CASUAL', 'خودمانی')], default='FRIENDLY', max_length=10, verbose_name='لحن')),
                ('max_sentences', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='حداکثر تعداد جمله')),
                ('use_emoji', models.BooleanField(default=False, verbose_name='استفاده از ایموجی')),
                ('signature', models.CharField(blank=True, default='', max_length=100, verbose_name='امضا')),
                ('include_link', models.BooleanField(default=True, verbose_name='لینک محصول در پیام')),
                ('extra_instructions', models.TextField(blank=True, default='', max_length=500, verbose_name='توضیحات سبک (اختیاری)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_style', to='businesses.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'سبک پیام',
                'verbose_name_plural': 'سبک\u200cهای پیام',
            },
        ),
    ]
