# Generated by Django 6.1.1 on 2026-10-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='ایمیل')),
                ('code', models.CharField(max_length=6, verbose_name='کد تأیید')),
                ('session_data', models.JSONField(default=dict, verbose_name='اطلاعات ثبت\u200cنام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش\u200cهای ناموفق')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین تلاش')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='مسدود تا')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
            ],
            options={
                'verbose_name': 'احراز هویت ایمیل',
                'verbose_name_plural': 'احراز هویت\u200cهای ایمیل',
                'ordering': ['-created_at'],
            },
        ),
    ]
