# Generated by Django 6.1.2 on 2026-10-09 17:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0007_message_style'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_toman', models.DecimalField(decimal_places=0, default=Decimal('100000'), max_digits=12, verbose_name='نرخ دلار (تومان)')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سود روی هزینه\u200cی واقعی (٪)')),
                ('charge_cached', models.BooleanField(default=False, help_text='پاسخ کش\u200cشده برای ما هزینه\u200cای ندارد؛ پیش\u200cفرض: رایگان برای فروشنده', verbose_name='کسر هزینه برای پاسخ\u200cهای کش\u200cشده')),
                ('enforce_balance', models.BooleanField(default=True, verbose_name='توقف تحلیل با اتمام اعتبار')),
                ('min_balance_toman', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='حداقل اعتبار برای ادامه\u200cی تحلیل (تومان)')),
                ('signup_credit_toman', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='اعتبار هدیه\u200cی ثبت\u200cنام (تومان)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات پرداخت',
                'verbose_name_plural': 'تنظیمات پرداخت',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام سرویس\u200cدهنده')),
                ('base_url', models.URLField(help_text='مثال: https://generativelanguage.googleapis.com/v1beta/openai', max_length=300, verbose_name='Base URL')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سرویس\u200cدهنده\u200cی مدل',
                'verbose_name_plural': 'سرویس\u200cدهنده\u200cهای مدل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_toman', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='موجودی (تومان)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='businesses.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TOPUP', 'شارژ'), ('USAGE', 'مصرف'), ('ADJUST', 'اصلاح دستی'), ('REFUND', 'بازگشت وجه'), ('GIFT', 'هدیه')], max_length=10, verbose_name='نوع')),
                ('amount_toman', models.DecimalField(decimal_places=2, help_text='مثبت = افزایش اعتبار، منفی = کسر', max_digits=18, verbose_name='مبلغ (تومان)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='موجودی بعد از تراکنش')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14, verbose_name='هزینه\u200cی واقعی ($)')),
                ('calls', models.PositiveIntegerField(default=0, verbose_name='تعداد فراخوانی')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='همان نامی که به API فرستاده می\u200cشود', max_length=150, verbose_name='شناسه مدل')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='نام نمایشی')),
                ('input_price_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت ورودی ($ / ۱M توکن)')),
                ('output_price_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت خروجی ($ / ۱M توکن)')),
                ('use_extract', models.BooleanField(default=False, verbose_name='استخراج نیاز / کارت محصول')),
                ('use_verify', models.BooleanField(default=False, verbose_name='تطبیق و راستی\u200cآزمایی')),
                ('use_reply', models.BooleanField(default=False, verbose_name='نوشتن پاسخ')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='عدد کمتر = اولویت بیشتر وقتی چند مدل یک نقش دارند', verbose_name='اولویت')),
                ('rpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف درخواست در دقیقه')),
                ('tpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف توکن در دقیقه')),
                ('rpd', models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف درخواست در روز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='billing.provider', verbose_name='سرویس\u200cدهنده')),
            ],
            options={
                'verbose_name': 'مدل هوش مصنوعی',
                'verbose_name_plural': 'مدل\u200cهای هوش مصنوعی',
                'ordering': ['priority', 'name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'name'), name='unique_model_per_provider')],
            },
        ),
    ]
