# Generated by Django 6.1.1 on 2026-10-05 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_daily_discovery_limit_and_more'),
        ('products', '0003_category_business_product_discovery_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMessageHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='چکیده یکتای پیام')),
                ('channel', models.CharField(choices=[('TELEGRAM', 'تلگرام'), ('X', 'X / توییتر')], max_length=20, verbose_name='کانال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'هش پیام پردازش\u200cشده',
                'verbose_name_plural': 'هش پیام\u200cهای پردازش\u200cشده',
            },
        ),
        migrations.CreateModel(
            name='CategoryBranchMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='کلیدواژه\u200cهای قصد خرید شاخه')),
                ('negative_keywords', models.JSONField(blank=True, default=list, verbose_name='کلمات کلیدی منفی (عدم تطابق)')),
                ('last_scanned_at', models.DateTimeField(auto_now=True, verbose_name='آخرین زمان پایش')),
                ('total_scanned_count', models.PositiveIntegerField(default=0, verbose_name='تعداد پیام\u200cهای بررسی\u200cشده')),
                ('leads_found_count', models.PositiveIntegerField(default=0, verbose_name='تعداد سرنخ\u200cهای کشف\u200cشده')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_memories', to='businesses.business', verbose_name='کسب\u200cوکار مرتبط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_memories', to='products.category', verbose_name='شاخه دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'حافظه پایش شاخه دسته\u200cبندی',
                'verbose_name_plural': 'حافظه\u200cهای پایش شاخه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='DiscoveredLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('TELEGRAM', 'تلگرام'), ('X', 'X (توییتر)')], max_length=20, verbose_name='شبکه اجتماعی')),
                ('lead_handle', models.CharField(max_length=150, verbose_name='شناسه کاربری مشتری')),
                ('lead_display_name', models.CharField(blank=True, max_length=150, verbose_name='نام کاربر')),
                ('post_url', models.URLField(blank=True, verbose_name='لینک پست یا گفت\u200cوگو')),
                ('content_snippet', models.TextField(verbose_name='متن درخواست یا سوال مشتری')),
                ('intent_score', models.PositiveSmallIntegerField(default=30, help_text='حداقل ۳۰ درصد برای ثبت در سیستم', verbose_name='احتمال خرید (درصد)')),
                ('intent_reasoning', models.TextField(blank=True, verbose_name='تحلیل هوش مصنوعی و علت انطباق')),
                ('matched_branch', models.CharField(blank=True, max_length=255, verbose_name='شاخه درختی منطبق')),
                ('outreach_mode', models.CharField(choices=[('DIRECT', 'دایرکت خصوصی'), ('COMMENT', 'کامنت / ریپلای عمومی')], default='DIRECT', max_length=20, verbose_name='نحوه ارتباط')),
                ('outreach_message', models.TextField(blank=True, verbose_name='پیش\u200cنویس پیام ارتباطی هوشمند')),
                ('outreach_status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس پیام'), ('SENT', 'ارسال موفق'), ('FAILED', 'خطا در ارسال')], default='DRAFT', max_length=20, verbose_name='وضعیت ارسال پیام')),
                ('sent_from_handle', models.CharField(blank=True, max_length=150, verbose_name='ارسال\u200cشده از حساب فروشنده')),
                ('status', models.CharField(choices=[('NEW', 'جدید (بررسی نشده)'), ('CONTACTED', 'پیام ارسال شد'), ('CONVERTED', 'مشتری نهایی'), ('IGNORED', 'نادیده گرفته شد')], default='NEW', max_length=20, verbose_name='وضعیت سرنخ')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان کشف')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین وضعیت')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_leads', to='businesses.business', verbose_name='کسب\u200cوکار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='products.product', verbose_name='کالای منطبق')),
            ],
            options={
                'verbose_name': 'سرنخ کشف\u200cشده',
                'verbose_name_plural': 'سرنخ\u200cهای کشف\u200cشده',
                'ordering': ['-intent_score', '-discovered_at'],
            },
        ),
    ]
