# Generated by Django 6.1.1 on 2026-10-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredlead',
            name='bot_agent_name',
            field=models.CharField(default='بات پیدا (@peyda_bot)', max_length=100, verbose_name='ایجنت / بات ارسال\u200cکننده'),
        ),
        migrations.AddField(
            model_name='discoveredlead',
            name='customer_reply',
            field=models.TextField(blank=True, verbose_name='پاسخ دریافت\u200cشده از مشتری'),
        ),
        migrations.AddField(
            model_name='discoveredlead',
            name='customer_reply_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان دریافت پاسخ مشتری'),
        ),
        migrations.AddField(
            model_name='discoveredlead',
            name='direct_link_sent',
            field=models.CharField(blank=True, max_length=255, verbose_name='لینک مستقیم محصول ارسالی در کامنت'),
        ),
        migrations.AddField(
            model_name='discoveredlead',
            name='guardrail_status',
            field=models.CharField(default='SAFE_IN_DOMAIN', max_length=50, verbose_name='وضعیت انطباق کانتکست محصول'),
        ),
        migrations.AddField(
            model_name='discoveredlead',
            name='is_conversation_capped',
            field=models.BooleanField(default=False, verbose_name='رسیدن به سقف ۱۰ پیام'),
        ),
        migrations.AddField(
            model_name='discoveredlead',
            name='message_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='حداکثر سقف مجاز: ۱۰ پیام', verbose_name='تعداد پیام\u200cهای تبادل\u200cشده'),
        ),
        migrations.AlterField(
            model_name='discoveredlead',
            name='outreach_message',
            field=models.TextField(blank=True, verbose_name='پیام ارسالی هوشمند ایجنت'),
        ),
        migrations.AlterField(
            model_name='discoveredlead',
            name='outreach_mode',
            field=models.CharField(choices=[('DIRECT', 'دایرکت خصوصی'), ('COMMENT', 'کامنت / ریپلای عمومی')], default='COMMENT', max_length=20, verbose_name='نحوه ارتباط'),
        ),
        migrations.AlterField(
            model_name='discoveredlead',
            name='outreach_status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس پیام'), ('SENT', 'ارسال موفق'), ('FAILED', 'خطا در ارسال')], default='SENT', max_length=20, verbose_name='وضعیت ارسال پیام'),
        ),
        migrations.AlterField(
            model_name='discoveredlead',
            name='sent_from_handle',
            field=models.CharField(blank=True, max_length=150, verbose_name='ارسال\u200cشده از حساب یا بات پیدا'),
        ),
    ]
