# Generated by Django 6.1.1 on 2026-10-06 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_discoveredlead_bot_agent_name_and_more'),
        ('products', '0003_category_business_product_discovery_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی خریدار')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='شماره تماس خریدار')),
                ('shipping_address', models.TextField(blank=True, verbose_name='آدرس تحویل سفارش')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت واحد (تومان)')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مبلغ کل (تومان)')),
                ('status', models.CharField(choices=[('PAID', 'پرداخت\u200cشده و نهایی'), ('PENDING', 'در انتظار تایید'), ('SHIPPED', 'ارسال\u200cشده')], default='PAID', max_length=20, verbose_name='وضعیت سفارش')),
                ('tracking_code', models.CharField(max_length=40, unique=True, verbose_name='کد پیگیری سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت سفارش')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discovery.discoveredlead', verbose_name='سرنخ خریدار مرتبط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سفارش خرید محصول',
                'verbose_name_plural': 'سفارشات خرید محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ روز')),
                ('outreach_sent_count', models.PositiveIntegerField(default=0, verbose_name='پیام\u200cهای ارسالی ایجنت')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='کلیک\u200cهای لینک محصول')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='بازدید صفحه محصول')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='تعداد سفارش / خرید')),
                ('sales_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مبلغ فروش (تومان)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آمار روزانه محصول',
                'verbose_name_plural': 'آمارهای روزانه محصولات',
                'ordering': ['-date', '-sales_amount'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
