# Generated by Django 6.1.1 on 2026-10-06 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_productorder_productdailymetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredlead',
            name='cost_toman',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه تومانی بررسی پیام'),
        ),
        migrations.AddField(
            model_name='discoveredlead',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='هزینه دلاری بررسی پیام'),
        ),
        migrations.AddField(
            model_name='discoveredlead',
            name='last_message_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ آخرین تبادل پیام'),
        ),
        migrations.AddField(
            model_name='discoveredlead',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0, verbose_name='توکن\u200cهای مصرفی بررسی پیام'),
        ),
        migrations.AlterField(
            model_name='discoveredlead',
            name='is_conversation_capped',
            field=models.BooleanField(default=False, verbose_name='رسیدن به سقف روزانه ۱۰ پیام'),
        ),
        migrations.AlterField(
            model_name='discoveredlead',
            name='message_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='حداکثر سقف مجاز روزانه: ۱۰ پیام', verbose_name='تعداد پیام\u200cهای تبادل\u200cشده امروز'),
        ),
    ]
