# Generated by Django 6.1.1 on 2026-10-08 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_business_target_locations_business_target_max_age_and_more'),
        ('discovery', '0004_discoveredlead_cost_toman_discoveredlead_cost_usd_and_more'),
        ('products', '0003_category_business_product_discovery_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='نام مشتری')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس')),
                ('external_user_id', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='شناسه کاربر در پلتفرم')),
                ('source_platform', models.CharField(choices=[('telegram', 'تلگرام (Telegram)'), ('x', 'ایکس / توییتر (X / Twitter)'), ('instagram', 'اینستاگرام (Instagram)'), ('divar', 'دیوار (Divar)'), ('other', 'سایر پلتفرم\u200cها')], db_index=True, default='telegram', max_length=30, verbose_name='پلتفرم مبدا')),
                ('source_profile_url', models.URLField(blank=True, verbose_name='آدرس پروفایل')),
                ('source_username', models.CharField(blank=True, max_length=150, verbose_name='نام کاربری در پلتفرم')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتای تکمیلی مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_customers', to='businesses.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'مشتری کشف\u200cشده',
                'verbose_name_plural': 'مشتریان کشف\u200cشده',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_snapshot', models.CharField(blank=True, max_length=255, verbose_name='عنوان شاخه در زمان کشف')),
                ('source_platform', models.CharField(choices=[('telegram', 'تلگرام (Telegram)'), ('x', 'ایکس / توییتر (X / Twitter)'), ('instagram', 'اینستاگرام (Instagram)'), ('divar', 'دیوار (Divar)'), ('other', 'سایر پلتفرم\u200cها')], db_index=True, default='telegram', max_length=30, verbose_name='پلتفرم مبدا')),
                ('source_message_id', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='شناسه پیام در پلتفرم')),
                ('source_raw_message', models.TextField(verbose_name='متن پیام کاربر در شبکه اجتماعی')),
                ('source_message_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال پیام در پلتفرم')),
                ('status', models.CharField(choices=[('NEW', 'جدید (New)'), ('QUALIFIED', 'تأیید شده (Qualified)'), ('REVIEWED', 'بررسی شده (Reviewed)'), ('CONTACTED', 'تماس گرفته شده (Contacted)'), ('CONVERTED', 'مشتری نهایی (Converted)'), ('REJECTED', 'رد شده (Rejected)')], db_index=True, default='QUALIFIED', max_length=20, verbose_name='وضعیت فرصت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد فرصت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='businesses.business', verbose_name='کسب\u200cوکار')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='products.category', verbose_name='دسته\u200cبندی مرتبط')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='discovery.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'فرصت فروش',
                'verbose_name_plural': 'فرصت\u200cهای فروش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('customer_message', 'متن پیام مشتری'), ('need_signal', 'سیگنال نیاز'), ('product_match', 'تطابق ویژگی\u200cهای محصول'), ('category_match', 'تطابق دسته\u200cبندی'), ('other', 'سایر شواهد')], default='customer_message', max_length=50, verbose_name='نوع شاهد')),
                ('content', models.TextField(verbose_name='محتوای شاهد متنی')),
                ('source_reference', models.CharField(blank=True, max_length=255, verbose_name='ارجاع یا منبع شاهد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='discovery.opportunity', verbose_name='فرصت مرتبط')),
            ],
            options={
                'verbose_name': 'شاهد متنی تصمیم',
                'verbose_name_plural': 'شواهد متنی تصمیمات',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need', models.TextField(verbose_name='نیاز یا مسئله اصلی مشتری')),
                ('intent_score', models.FloatField(default=0.0, verbose_name='امتیاز قصد خرید (بین ۰ تا ۱)')),
                ('product_fit_score', models.FloatField(default=0.0, verbose_name='امتیاز تطابق با کاتالوگ (بین ۰ تا ۱)')),
                ('confidence', models.FloatField(default=0.0, verbose_name='میزان اطمینان کلی هوش مصنوعی (بین ۰ تا ۱)')),
                ('why_selected', models.TextField(verbose_name='دلیل انتخاب این مشتری (توضیح کوتاه و شفاف)')),
                ('suggested_reply', models.TextField(blank=True, verbose_name='پیش\u200cنویس پیام پیشنهادی هوش مصنوعی برای ارسال توسط فروشنده')),
                ('model_name', models.CharField(default='llama-3.3-70b-versatile', max_length=100, verbose_name='نام مدل زبانی')),
                ('model_version', models.CharField(blank=True, max_length=50, verbose_name='نسخه مدل')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='توکن\u200cهای مصرفی')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='هزینه دلاری')),
                ('cost_toman', models.PositiveIntegerField(default=0, verbose_name='هزینه تومانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت تحلیل')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='discovery.opportunity', verbose_name='فرصت مرتبط')),
            ],
            options={
                'verbose_name': 'تحلیل هوش مصنوعی فرصت',
                'verbose_name_plural': 'تحلیل\u200cهای هوش مصنوعی فرصت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='OpportunityProductMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0, verbose_name='امتیاز انطباق کالا (بین ۰ تا ۱)')),
                ('recommendation_reason', models.TextField(blank=True, verbose_name='علت پیشنهاد این کالا')),
                ('rank', models.PositiveSmallIntegerField(default=1, verbose_name='رتبه در بین پیشنهادات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_matches', to='discovery.opportunity', verbose_name='فرصت مرتبط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_matches', to='products.product', verbose_name='محصول پیشنهادی')),
            ],
            options={
                'verbose_name': 'انطباق محصول با فرصت',
                'verbose_name_plural': 'انطباق\u200cهای محصول با فرصت\u200cها',
                'ordering': ['rank', '-match_score'],
            },
        ),
    ]
