# Generated by Django 6.1.1 on 2026-10-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0005_customer_opportunity_evidence_aianalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='category_confidence',
            field=models.FloatField(default=0.0, verbose_name='ضریب اطمینان تطابق دسته (بین ۰ تا ۱)'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='category_path_snapshot',
            field=models.CharField(blank=True, max_length=500, verbose_name='مسیر کامل شاخه در زمان کشف'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='normalized_message',
            field=models.TextField(blank=True, verbose_name='متن پیام نرمال\u200cشده'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='trace_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='متادیتای ردیابی و لاگ پردازش'),
        ),
        migrations.AddField(
            model_name='opportunityproductmatch',
            name='matching_attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='ویژگی\u200cهای منطبق کالا'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('MATCHED', 'منطبق با محصول (Matched)'), ('CATEGORY_UNCERTAIN', 'دسته\u200cبندی نامطمئن (Category Uncertain)'), ('NO_PRODUCT_MATCH', 'بدون تطابق محصول (No Product Match)'), ('NOT_A_BUYER', 'غیر خریدار / رد شده (Not a Buyer)'), ('INVALID_INPUT', 'ورودی نامعتبر (Invalid Input)'), ('DUPLICATE', 'پیام تکراری (Duplicate)'), ('NEW', 'جدید (New)'), ('QUALIFIED', 'تأیید شده (Qualified)'), ('REVIEWED', 'بررسی شده (Reviewed)'), ('CONTACTED', 'تماس گرفته شده (Contacted)'), ('CONVERTED', 'مشتری نهایی (Converted)'), ('REJECTED', 'رد شده (Rejected)')], db_index=True, default='QUALIFIED', max_length=30, verbose_name='وضعیت فرصت'),
        ),
    ]
