# Generated by Django 6.1.1 on 2026-10-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_catalog_version_business_taxonomy_version'),
        ('discovery', '0006_opportunity_category_confidence_and_more'),
        ('products', '0004_category_depth_category_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'تلگرام (Telegram)')], default='telegram', max_length=20, verbose_name='پلتفرم')),
                ('community_type', models.CharField(choices=[('CHANNEL', 'کانال تلگرام'), ('GROUP', 'گروه / سوپرگروه تلگرام')], default='CHANNEL', max_length=20, verbose_name='نوع جامعه')),
                ('name', models.CharField(max_length=255, verbose_name='نام کانال یا گروه')),
                ('handle_or_link', models.CharField(max_length=255, verbose_name='آیدی یا لینک تلگرام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات و حوزه فعالیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال برای پایش')),
                ('members_count', models.PositiveIntegerField(default=0, verbose_name='تعداد اعضا / مخاطبان')),
                ('messages_scanned_count', models.PositiveIntegerField(default=0, verbose_name='پیام\u200cهای رصدشده')),
                ('leads_discovered_count', models.PositiveIntegerField(default=0, verbose_name='سرنخ\u200cهای کشف\u200cشده')),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین زمان پایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_communities', to='businesses.business', verbose_name='کسب\u200cوکار')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='products.category', verbose_name='دسته\u200cبندی مرتبط')),
            ],
            options={
                'verbose_name': 'جامعه آنلاین پایش\u200cشده',
                'verbose_name_plural': 'جوامع آنلاین پایش\u200cشده',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
