# Generated by Django 6.1.2 on 2026-10-08 23:32

import django.db.models.deletion
from django.db import migrations, models


OLD_STATUS = {"QUALIFIED": "NEW", "MATCHED": "NEW", "CATEGORY_UNCERTAIN": "NEW", "NO_PRODUCT_MATCH": "NEW",
              "NOT_A_BUYER": "REJECTED", "INVALID_INPUT": "REJECTED", "DUPLICATE": "REJECTED"}


def map_old_statuses(apps, schema_editor):
    Opportunity = apps.get_model("discovery", "Opportunity")
    for old, new in OLD_STATUS.items():
        Opportunity.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0007_monitoredcommunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorybranchmemory',
            name='business',
        ),
        migrations.RemoveField(
            model_name='categorybranchmemory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='discoveredlead',
            name='business',
        ),
        migrations.RemoveField(
            model_name='discoveredlead',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='lead',
        ),
        migrations.DeleteModel(
            name='ProcessedMessageHash',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='engine_opportunity_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='شناسه فرصت در موتور تحلیل'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضای فرصت'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discovery.opportunity', verbose_name='فرصت فروش مرتبط'),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام مدل زبانی'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('NEW', 'جدید'), ('REVIEWED', 'بررسی شده'), ('CONTACTED', 'تماس گرفته شده'), ('CONVERTED', 'مشتری نهایی'), ('REJECTED', 'رد شده'), ('RESOLVED', 'نیاز برطرف شد'), ('EXPIRED', 'منقضی شده')], db_index=True, default='NEW', max_length=30, verbose_name='وضعیت فرصت'),
        ),
        migrations.DeleteModel(
            name='CategoryBranchMemory',
        ),
        migrations.DeleteModel(
            name='DiscoveredLead',
        ),
        migrations.RunPython(map_old_statuses, migrations.RunPython.noop),
    ]
