# Generated by Django 6.1.2 on 2026-10-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0008_engine_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineSyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='opportunities', max_length=64, unique=True)),
                ('position', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
