# Generated by Django 6.1.2 on 2026-10-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0009_engine_sync_cursor'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredcommunity',
            name='sync_error',
            field=models.TextField(blank=True, default='', verbose_name='خطای اتصال'),
        ),
        migrations.AddField(
            model_name='monitoredcommunity',
            name='sync_status',
            field=models.CharField(choices=[('PENDING', 'در صف اتصال'), ('ACTIVE', 'در حال پایش'), ('PAUSED', 'متوقف'), ('ERROR', 'خطا در اتصال')], default='PENDING', max_length=10, verbose_name='وضعیت اتصال کراولر'),
        ),
        migrations.AddField(
            model_name='monitoredcommunity',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='شناسه چت تلگرام'),
        ),
    ]
