# Generated by Django 6.1.2 on 2026-10-09 12:31

import django.db.models.deletion
from django.db import migrations, models

from apps.discovery.sources import normalize_link


def fill_normalized_links(apps, schema_editor):
    MonitoredCommunity = apps.get_model("discovery", "MonitoredCommunity")
    for c in MonitoredCommunity.objects.all().only("id", "handle_or_link"):
        MonitoredCommunity.objects.filter(id=c.id).update(normalized_link=normalize_link(c.handle_or_link))


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_engine_cleanup'),
        ('discovery', '0010_monitoredcommunity_crawler_sync'),
        ('products', '0005_engine_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoredcommunity',
            options={'ordering': ['-is_active', '-created_at'], 'verbose_name': 'منبع پایش (گروه/کانال تلگرام)', 'verbose_name_plural': 'منابع پایش (گروه\u200cها و کانال\u200cهای تلگرام)'},
        ),
        migrations.AddField(
            model_name='monitoredcommunity',
            name='normalized_link',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='monitoredcommunity',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', 'عمومی (برای همه\u200cی فروشنده\u200cها)'), ('PRIVATE', 'اختصاصی فروشنده')], db_index=True, default='PRIVATE', max_length=10, verbose_name='نوع منبع'),
        ),
        migrations.AlterField(
            model_name='monitoredcommunity',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitored_communities', to='businesses.business', verbose_name='کسب\u200cوکار (برای منبع عمومی خالی)'),
        ),
        migrations.AlterField(
            model_name='monitoredcommunity',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='نام کانال یا گروه'),
        ),
        migrations.RunPython(fill_normalized_links, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='monitoredcommunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('business__isnull', True), ('scope', 'GLOBAL')), models.Q(('business__isnull', False), ('scope', 'PRIVATE')), _connector='OR'), name='community_scope_matches_owner'),
        ),
    ]
